// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/supabase_auth_test/PlasmicGlobalContextsProvider";
import { ScreenVariantProvider } from "../components/plasmic/supabase_auth_test/PlasmicGlobalVariant__Screen";
import { PlasmicSignup } from "../components/plasmic/supabase_auth_test/PlasmicSignup";
import { useRouter } from "next/router";

function Signup() {

  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicSignup />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Signup;
